---
- name: removing ports
  hosts: web
  gather_facts: no
  become: yes
  tasks:
    - name: using firewalld module
      firewalld:
         zone: public
         port: "{{ item }}"
         permanent: yes
         state: absent
         immediate: yes
      loop:
        - 80/tcp
        - 8082/tcp
        - 8085/tcp
        - 8086/tcp
        - 8081/tcp

