---
- name: Removing ports using firewall-cmd
  hosts: web
  gather_facts: no
  become: yes
  tasks:
    - name: Remove ports manually using firewall-cmd
      shell: |
        firewall-cmd --permanent --remove-port={{ item }}
        firewall-cmd --remove-port={{ item }}
      loop:
        - 80/tcp
        - 8082/tcp
        - 8085/tcp
        - 8086/tcp
        - 8081/tcp

