---
- name: uninstalling packages
  hosts: web
  gather_facts: no
  become: yes
  tasks:
    - name: uninstalling
      yum: 
        name: "{{ item }}"
        state: present
      loop:
         - httpd
         - nginx
         - samba
         - postgresql-server
    - name: service starting
      service:
          name: "{{ item }}"
          state: started
      loop:
        - httpd
        - nginx
        - postgresql
    

