---
- name: upgrading all packages excpt kernal and foo related 
  hosts: web
  gather_facts: no
  become: yes
  tasks:
    - name: using yum
      yum:
       name: '*'
       state: latest
       exclude: kernal*,foo*
      register: upgrade_output
    - name: creating file
      copy:
        content: "{{ upgrade_output }}"
        dest: /tmp/upgrade_ouput.txt 
