---
- name: Installing web application
  yum:
    name: httpd
    state: present

- name: Start and enable the httpd service
  service:
    name: httpd
    state: started
    enabled: yes

- name: Copying index.html file
  copy:
    src: apache/files/index.html
    dest: /var/www/html/index.html
  notify:
    - Restart httpd


# tasks file for apache
